name: Push deploy

on:
  push:
    branches:
      - main  # メインブランチへのプッシュ時に実行
  workflow_dispatch:  # 手動でワークフローをトリガー

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"  # 使用するNode.jsのバージョンを指定

      - name: Install dependencies
        run: npm install  # npmパッケージのインストール

      - name: Run build
        run: npm run build  # Viteによるビルドを実行

      - name: Verify dist directory
        run: ls -la dist  # distディレクトリの内容を確認

  deploy:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-latest
    needs: build  # buildジョブが完了した後に実行
    steps:
          - name: Verify dist directory2
        run: ls -la dist  # distディレクトリの内容を確認

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify dist directory3
        run: ls -la dist  # distディレクトリの内容を確認

      - name: Setup Node.js and cache
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"  # npmのキャッシュを使用して依存関係を高速化

                - name: Verify dist directory4
        run: ls -la dist  # distディレクトリの内容を確認

      - name: Install firebase-tools
        run: npm install --save-dev firebase-tools  # Firebase CLIのインストール

              - name: Verify dist directory5
        run: ls -la dist  # distディレクトリの内容を確認

      - name: Decode Firebase service account key
        run: |
          echo "${{ secrets.FIREBASE_KEY }}" | base64 -d > ./firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-key.json" >> $GITHUB_ENV

                - name: Verify dist directory6
        run: ls -la dist  # distディレクトリの内容を確認

      - name: Select Firebase project
        run: ./node_modules/.bin/firebase use ${{ secrets.FIREBASE_PROJECT_ID }}  # Firebaseプロジェクトの選択

              - name: Verify dist directory7
        run: ls -la dist  # distディレクトリの内容を確認

      - name: Deploy to Firebase Hosting
        run: |
          ./node_modules/.bin/firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  # Firebaseトークンの設定
          FIREBASE_CLI_EXPERIMENTS: webframeworks  # Firebase CLIの実験的機能の有効化

      - name: Validate deployment
        run: echo "Deployment completed successfully!"

  cleanup:
    name: Final cleanup
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Cleanup Firebase service account key
        run: rm ./firebase-key.json  # ジョブ終了時にFirebaseのサービスアカウントキーを削除
