name: Push deploy

on:
  push:
    branches:
      - main  # メインブランチへのプッシュ時に実行
  workflow_dispatch:  # 手動でワークフローをトリガー

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Verify dist directory
        run: |
          if [ ! -d "dist" ]; then
            echo "::error::dist directory not found after build!"
            exit 1
          fi


  deploy:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-latest
    needs: build  # buildジョブが完了した後に実行
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js and cache
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"

      - name: Verify dist directory before deploy
        run: |
          if [ ! -d "dist" ]; then
            echo "::error::dist directory not found before deploy!"
            exit 1
          fi

      - name: Install firebase-tools
        run: npm install --save-dev firebase-tools

      - name: Decode Firebase service account key
        run: |
          echo "${{ secrets.FIREBASE_KEY }}" | base64 -d > ./firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-key.json" >> $GITHUB_ENV

      - name: Select Firebase project
        run: ./node_modules/.bin/firebase use ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Deploy to Firebase Hosting
        run: |
          ./node_modules/.bin/firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_CLI_EXPERIMENTS: webframeworks

      - name: Validate deployment
        run: echo "Deployment completed successfully!"
        
  cleanup:
    name: Final cleanup
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Cleanup Firebase service account key
        run: rm ./firebase-key.json  # ジョブ終了時にFirebaseのサービスアカウントキーを削除
